name       : tar
version    : '1.35'
release    : 15
source     :
    - https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz : 4d62ff37342ec7aed748535323930c7cf94acf71c3591882b26a7ea50f3edc16
homepage   : https://www.gnu.org/software/tar/
license    : GPL-3.0-or-later
component  : system.base
summary    : tar (Create and extract archives)
description: |
    The Tar program provides the ability to create tar archives, as well as various other kinds of manipulation. For example, you can use Tar on previously created archives to extract files, to store additional files, or to update or list files which were already stored.
builddeps  :
    - pkgconfig(libacl)
setup      : |
    %apply_patches

    %configure --libexecdir=/usr/sbin
build      : |
    %make
install    : |
    %make_install

    # Usr-Merge
    install -D -d -m 00755 $installdir/bin
    ln -sv /usr/bin/tar $installdir/bin/tar
check      : |
    unset LD_PRELOAD
    %make check
