name       : tar
version    : '1.30'
release    : 6
source     :
    - https://ftp.gnu.org/gnu/tar/tar-1.30.tar.xz : f1bf92dbb1e1ab27911a861ea8dde8208ee774866c46c0bb6ead41f4d1f4d2d3
homepage   : https://www.gnu.org/software/tar/
license    : GPL-3.0
component  : system.base
summary    : tar (Create and extract archives)
description: |
    The Tar program provides the ability to create tar archives, as well as various other kinds of manipulation. For example, you can use Tar on previously created archives to extract files, to store additional files, or to update or list files which were already stored.
setup      : |
    FORCE_UNSAFE_CONFIGURE=1 %configure --libexecdir=/usr/sbin --bindir=/bin
build      : |
    %make
install    : |
    %make_install
