name       : tar
version    : '1.33'
release    : 12
source     :
    - https://ftp.gnu.org/gnu/tar/tar-1.33.tar.xz : 66a8344b1dc83a411d311bd1547e0176e56cc311f28ee94a30f84dafb3d9067e
homepage   : https://www.gnu.org/software/tar/
license    : GPL-3.0-or-later
component  : system.base
summary    : tar (Create and extract archives)
description: |
    The Tar program provides the ability to create tar archives, as well as various other kinds of manipulation. For example, you can use Tar on previously created archives to extract files, to store additional files, or to update or list files which were already stored.
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-failing-tests.patch

    FORCE_UNSAFE_CONFIGURE=1 %configure --libexecdir=/usr/sbin --bindir=/bin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
