name       : tar
version    : 1.29
release    : 5
source     :
    - http://mirrors.kernel.org/gnu/tar/tar-1.29.tar.xz : 402dcfd0022fd7a1f2c5611f5c61af1cd84910a760a44a688e18ddbff4e9f024
homepage   : http://www.gnu.org/software/tar
license    :
    - GPL-3.0
component  : system.base
summary    : tar (Create and extract archives)
description: |
    The Tar program provides the ability to create tar archives, as well as various other kinds of manipulation. For example, you can use Tar on previously created archives to extract files, to store additional files, or to update or list files which were already stored.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2016-6321.patch
    FORCE_UNSAFE_CONFIGURE=1 %configure --libexecdir=/usr/sbin --bindir=/bin
build      : |
    %make
install    : |
    %make_install
